### ISSUE TITLE
Add ->set_default_value_backend( $default_value ) ->set_default_value_front_end( $default_value ) 

### ISSUE THREAD

**Issue by BenBroide** [htmlburger/carbon-fields#559]
## Version

  - Carbon Fields: 2.2
  - WordPress: 4.9.7
  - PHP: 7

## Expected Behavior
They should be a way to set a default value for the backend end post screen, and a default value do display in front end (via carbon_get_post_meta or rest api).

## Actual Behavior
When you set a default value, if no value in DB the default value will be set in the carbon edit screen and in rest api / `carbon_get_post_meta`

## Comments
The reason:
I have a projects which has a country field, and state field. The country field always has a value, the state field has a value only if country is united states.
The problem happens when I set a default value for a state, for example, if I will set the default state for as "NY", and I will get the fields for a country that is not United states, `carbon_get_post_meta` will return "NY" for the state field because that is the default value.
If it would possible to set a different default value for the admin edit fields, and a different default value to `carbon_get_post_meta` that would be great.

Thanks!

**Comment by deqngeorgiev** [comment]
Hi @BenBroide,

I think it wouldn't be intuitive to have different values for the administration and the front end. When you set a value in the administration you will expect to use the same value in your logic or front end.

Also, I believe that using different values will not solve your problem. You will still get the default value when the country is not the United States.

In my opinion, you should change your logic and use the State field value only when the country is the United States. Also, you can consider using `set_conditional_logic()` method to show the state field only for the United States.

If you need further help I will be happy to help.

**Comment by BenBroide** [comment]
Hi @deqngeorgiev ,
It could be a function to change the default value in front end only if that function is called. So it won't change the behavior of of set_default_values if not set,  so this would be intuitive. 
To have that additional would fix the issue. 
This is important, I raised this issue here because I fixed recently bugs in a few projects which were caused because the default value showed when the field was not saved and the desired output in front end should have be empty string,  not the default value for the back end.

**Comment by deqngeorgiev** [comment]
I'm still not sure what you want to achieve with the different method for the front end default value.

Currently, when `set_default_value` method is used, the value wouldn't be saved to the database until the page where the field is used is saved. So the value in the front end would be empty.

Can you, please, provide information about the bugs which you fixed with the `set_default_value` and we will think of a solution to the problem?

**Comment by jorostoyanov** [comment]
Closing due to inactivity
