### ISSUE TITLE
Unknown field type "oembed"

### ISSUE THREAD

**Issue by martinglover** [htmlburger/carbon-fields#947]
## Version

  - Carbon Fields: 3.2.1
  - WordPress: 5.5.3
  - PHP: 7.4

## Expected Behavior
To be able to create an oembed field using

```php
Field::make('oembed', 'embed-field', 'Embed Video');
or
Field::make_oembed('embed-field', 'Embed Video');
```

## Actual Behavior
Unknown field type "oembed".

## Container definition
```php
Container::make_theme_options('theme-options', 'Theme Options')
->add_fields([
    Field::make_oembed('embed-field', 'Embed Video')
]);
```

## Steps to Reproduce the Problem

  1. Create container that tries to use an oembed

## Comments
This looks to be linked to the change made in https://github.com/htmlburger/carbon-fields/pull/915 the field factory can no longer generate the class name

**Comment by jorostoyanov** [comment]
Hi @martinglover 

By using either of the two code samples I had no problems in using the oEmbed field.

Can you clarify whether you are using the plugin or the composer package?

**Comment by shvlv** [comment]
Confirm this issue.
Dirty hack to https://github.com/htmlburger/carbon-fields/blob/development/core/Helper/Helper.php#L426 fix this.
```php
if ($classlike_type === 'Oembed') {
     $classlike_type = 'OEmbed';
}
```

**Comment by martinglover** [comment]
Hi @jorostoyanov 

I'm using the composer install

I'm running Ubuntu 20.04 which is a case sensitive file system whether that affects reproduction of the issue.

The helper `normalize_type` converts to lower case so is looking for class `Oembed` while the class is `OEmbed`

The simplest fix I have at the moment is to rename the `OEmbed_Field` file and class to `Oembed_Field`

**Comment by hybridvision** [comment]
Also confirming this issue - I didn't see it in my local development environment (non case-sensitive file system) but I had the error on the production server running Linux.

I followed @martinglover's suggestion to rename the file as a temporary fix.

**Comment by jorostoyanov** [comment]
This has been fixed in https://github.com/htmlburger/carbon-fields/pull/915 and is available in the latest release :)

**Comment by zessx** [comment]
@jorostoyanov : @martinglover is already using the 3.2.1 release (which ships the fix), please reopen.

**Comment by martinglover** [comment]
@jorostoyanov I think you've misunderstood #915 has caused the issue
@zessx is right I'm already using 3.2.1

**Comment by nk-o** [comment]
@jorostoyanov still see this bug in v3.2.1. Please, fix it 🥴

**Comment by golchha21** [comment]
Installation:

- Carbon Fields: 3.2.3
- WordPress: 5.7
- PHP: 7.4

![image](https://user-images.githubusercontent.com/772400/111193122-d6084700-85df-11eb-8e55-f5a8be7d5ffc.png)

**Comment by Huynhhuynh** [comment]
I also have the same problem

* Carbon Fields: 3.2.3
* WordPress: 5.7
* PHP: 7.4
![image](https://user-images.githubusercontent.com/29724255/111870424-3ff56780-89b7-11eb-8511-c13c7c9c0819.png)

**Comment by zessx** [comment]
@jorostoyanov Ping to reopen…
